version: "3.8"

services:
  db:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task_manager_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: task_manager_api
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/task_manager
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: clave_super_secreta
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: